### ISSUE TITLE
[REQUEST] Bloqueo de cuenta por intentos fallidos.

### ISSUE THREAD

**Issue by manucabral** [TeamParches/parches-chat#22]
Al intentar ingresar su cuenta y fallar datos de ingreso varias veces que la cuenta se bloquee y manda un alerta al mail o teléfono.

**Comment by leoarayav** [comment]
Entonces este bloqueo vendría siendo general? Lets go then.

**Comment by manucabral** [comment]
La idea lo propuso @AlexisViera lo transferí a un issue, por lo que entiendo seria un bloqueo total de la cuenta hasta que se pueda recuperar mediante e-mail o si llegamos a tener un buen sistema de mensajería por número de celular.
