### ISSUE TITLE
[REQUEST] Agregar información adicional de un usuario.

### ISSUE THREAD

**Issue by manucabral** [TeamParches/parches-chat#39]
Permitir que cada usuario pueda poner una descripción de su cuenta.

**Comment by leoarayav** [comment]
Informacion adicional te refieres a una descripción del usuario?

**Comment by manucabral** [comment]
> Informacion adicional te refieres a una descripción del usuario?

Se refiere al custom status del usuario

**Comment by manucabral** [comment]
Debido al cambio de estructura este issue no tiene que estar en este repositorio.
[Nuevo repositorio para backend](https://github.com/TeamParches/parches-chat-backend/tree/main)
