### ISSUE TITLE
[REQUEST] Agregar suscripción de escucha de escribiendo mensajes

### ISSUE THREAD

**Issue by GabrielCarames** [TeamParches/parches-chat#40]
Si tengo agregado a un amigo o estoy en un grupo, se tiene que escuchar por medio de una nueva suscripción si ese amigo o algún integrante del grupo está escribiendo.

**Comment by manucabral** [comment]
Debido al cambio de estructura este issue no tiene que estar en este repositorio.
[Nuevo repositorio para backend](https://github.com/TeamParches/parches-chat-backend/tree/main)
